[package]
name = "resvg"
# When updating version, also modify html_root_url in the lib.rs and in the README
version = "0.2.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg", "render", "raster"]
license = "MPL-2.0"
description = "An SVG rendering library."
documentation = "https://docs.rs/resvg/"
repository = "https://github.com/RazrFalcon/resvg"
readme = "README.md"
categories = ["multimedia::images"]

[workspace]
members = [
    "capi",
    "tools/rendersvg"
]
exclude = [
    "examples/cairo-rs",
    "testing_tools",
    "workdir-qt", # for CI tests
    "workdir-cairo" # for CI tests
]

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
log = "0.4"
usvg = { git = "https://github.com/RazrFalcon/usvg", rev = "0cf6f00" }
#usvg = { path = "../usvg" }
# cairo backend
cairo-rs = { version = "0.4.1", features = ["png"], optional = true }
image = { version = "0.18", default-features = false, features = ["jpeg", "png_codec"], optional = true }
pango = { version = "0.4", optional = true }
pangocairo = { version = "0.5", optional = true }
# qt backend
resvg-qt = { version = "0.2.1", optional = true }

[features]
cairo-backend = ["cairo-rs", "pango", "pangocairo", "image"]
qt-backend = ["resvg-qt"]

[lib]
doctest = false

[profile.release]
lto = true
