[package]
name = "usvg"
version = "0.8.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing-tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[dependencies]
base64 = "0.10"
data-url = "0.1"
flate2 = { version = "1.0.11", default-features = false, features = ["rust_backend"]}
kurbo = "0.2.3"
log = "0.4"
rctree = "0.3"
xmlwriter = "0.1"

# for svgtree
roxmltree = "0.7"
simplecss = "0.2"
siphasher = "0.2.3"
svgtypes = "0.5"

# for text to path
harfbuzz_rs = "1.0"
memmap = "0.7"
ttf-parser = "0.2.2"
unicode-bidi = "0.3"
unicode-script = "0.3"
unicode-vo = "0.1"
