[package]
name = "usvg"
version = "0.14.0"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["svg"]
license = "MPL-2.0"
edition = "2018"
description = "An SVG simplification library."
categories = ["multimedia::images"]
repository = "https://github.com/RazrFalcon/resvg"
documentation = "https://docs.rs/usvg/"
readme = "README.md"
exclude = ["testing-tools/**"]
workspace = ".."

[badges]
travis-ci = { repository = "RazrFalcon/resvg" }

[[bin]]
name = "usvg"
required-features = ["system-fonts", "text"]

[dependencies]
base64 = "0.13"
data-url = "0.1"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"]}
kurbo = "0.8"
log = "0.4"
pico-args = "0.4"
rctree = "0.3"
xmlwriter = "0.1"

# for svgtree
roxmltree = "0.14"
simplecss = "0.2"
siphasher = "0.2"
svgtypes = "0.5"

# for text to path
fontdb = { version = "0.5.1", optional = true, default-features = false }
rustybuzz = { version = "0.3", optional = true }
memmap2 = { version = "0.2", optional = true }
ttf-parser = { version = "0.12", optional = true }
unicode-bidi = { version = "0.3", optional = true }
unicode-script = { version = "0.5", optional = true }
unicode-vo = { version = "0.1", optional = true }

[features]
default = ["system-fonts", "text"]
text = [
    "fontdb",
    "rustybuzz",
    "ttf-parser",
    "unicode-bidi",
    "unicode-script",
    "unicode-vo",
]
system-fonts = [
    "fontdb/fs",
    "memmap2",
]
