[package]
name = "explorer-thumbnailer"
version = "0.41.0"
authors = ["gentoo90 <gentoo90@gmail.com>"]
license = "MPL-2.0"
edition = "2021"
publish = false

[workspace]

[dependencies]
com = "0.2"
winapi = { version = "0.3.9", features = ["impl-default", "objidlbase", "windef", "wingdi"] }
log = "0.4"
winlog = "0.2"
resvg = { path = "../../crates/resvg" }

[lib]
# name can only be "server.dll", see https://github.com/microsoft/com-rs/issues/157
name = "server"
crate-type = ["rlib", "cdylib"]
